# Generated by Django 5.2.6 on 2025-10-02 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=100)),
                ('element_type', models.CharField(max_length=50)),
                ('rarity', models.CharField(max_length=50)),
                ('is_hatched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eggs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to=settings.AUTH_USER_MODEL)),
                ('egg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinosaur', to='core.egg')),
                ('traits', models.ManyToManyField(blank=True, related_name='dinosaurs', to='core.trait')),
            ],
        ),
        migrations.CreateModel(
            name='RaiseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('feed', 'Feed'), ('play', 'Play'), ('train', 'Train')], max_length=20)),
                ('outcome', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dinosaur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.dinosaur')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dinosaur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.dinosaur')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
