# Generated by Django 5.2.6 on 2025-10-02 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='mood_impact',
            field=models.CharField(blank=True, help_text='How this trait influences mood (e.g. +Playful, -Calm)', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='egg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinosaur', to='core.egg'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('hungry', 'Hungry'), ('playful', 'Playful'), ('tired', 'Tired')], default='happy', max_length=20),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='stage',
            field=models.CharField(choices=[('hatchling', 'Hatchling'), ('juvenile', 'Juvenile'), ('adult', 'Adult')], default='hatchling', max_length=20),
        ),
    ]
