# Generated by Django 5.2.6 on 2025-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trait_mood_impact_alter_dinosaur_egg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
