# Generated by Django 4.2.24 on 2025-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dinosaur_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='leaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='egg',
            name='twigs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
