# Generated by Django 5.2.6 on 2025-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_egg_leaves_egg_twigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
