# Generated by Django 4.2.24 on 2025-10-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_egg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='dinosaur',
        ),
        migrations.AddField(
            model_name='trade',
            name='receiver_dinosaur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_dino_trades', to='core.dinosaur'),
        ),
        migrations.AddField(
            model_name='trade',
            name='receiver_egg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_trades', to='core.egg'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sender_dinosaur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_dino_trades', to='core.dinosaur'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sender_egg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_trades', to='core.egg'),
        ),
        migrations.AlterField(
            model_name='dinosaur',
            name='stage',
            field=models.CharField(choices=[('juvenile', 'Juvenile'), ('adult', 'Adult')], default='juvenile', max_length=20),
        ),
    ]
